// Code generated by goctl. DO NOT EDIT.

package sysmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"pure-go-zero-admin/common/enumx"
)

var (
	sysUserFieldNames          = builder.RawFieldNames(&SysUser{})
	sysUserRows                = strings.Join(sysUserFieldNames, ",")
	sysUserRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysUserRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysUserModel interface {
		Insert(ctx context.Context, data *SysUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysUser, error)
		FindOneByName(ctx context.Context, name string) (*SysUser, error)
		FindAll(ctx context.Context, sysUserquery *SysUserQuery, Current int64, PageSize int64) (*[]SysUserList, error)
		Count(ctx context.Context, sysUserQuery *SysUserQuery) (int64, error)
		Update(ctx context.Context, data *SysUser) error
		Delete(ctx context.Context, id int64) error
		DeleteUser(ctx context.Context, data *SysUser ) error
	}

	defaultSysUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysUser struct {
		Id             int64     `db:"id"`               // 编号
		Name           string    `db:"name"`             // 用户名
		NickName       string    `db:"nick_name"`        // 昵称
		Avatar         string    `db:"avatar"`           // 头像
		Password       string    `db:"password"`         // 密码
		Salt           string    `db:"salt"`             // 加密盐
		Email          string    `db:"email"`            // 邮箱
		Mobile         string    `db:"mobile"`           // 手机号
		Status         int64     `db:"status"`           // 状态  0：禁用   1：正常
		DeptId         int64     `db:"dept_id"`          // 机构ID
		CreateBy       string    `db:"create_by"`        // 创建人
		CreateTime     time.Time `db:"create_time"`      // 创建时间
		LastUpdateBy   string    `db:"last_update_by"`   // 更新人
		LastUpdateTime time.Time `db:"last_update_time"` // 更新时间
		DelFlag        int64     `db:"del_flag"`         // 是否删除  -1：已删除  0：正常
		JobId          int64     `db:"job_id"`           // 岗位Id
	}

	SysUserQuery struct {
		Name     string `db:"name"`      // 用户名
		NickName string `db:"nick_name"` // 昵称
		Email    string `db:"email"`     // 邮箱
		Mobile   string `db:"mobile"`    // 手机号
		Status   int64  `db:"status"`    // 状态  0：禁用   1：正常
	}

	SysUserList struct {
		Id             int64     `db:"id"`               // 编号
		Name           string    `db:"name"`             // 用户名
		NickName       string    `db:"nick_name"`        // 昵称
		Avatar         string    `db:"avatar"`           // 头像
		Password       string    `db:"password"`         // 密码
		Salt           string    `db:"salt"`             // 加密盐
		Email          string    `db:"email"`            // 邮箱
		Mobile         string    `db:"mobile"`           // 手机号
		Status         int64     `db:"status"`           // 状态  0：禁用   1：正常
		DeptId         int64     `db:"dept_id"`          // 机构ID
		CreateBy       string    `db:"create_by"`        // 创建人
		CreateTime     time.Time `db:"create_time"`      // 创建时间
		LastUpdateBy   string    `db:"last_update_by"`   // 更新人
		LastUpdateTime time.Time `db:"last_update_time"` // 更新时间
		DelFlag        int64     `db:"del_flag"`         // 是否删除  -1：已删除  0：正常
	}
)

func newSysUserModel(conn sqlx.SqlConn) *defaultSysUserModel {
	return &defaultSysUserModel{
		conn:  conn,
		table: "`sys_user`",
	}
}

func (m *defaultSysUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysUserModel) DeleteUser(ctx context.Context, data *SysUser ) error {
	query := fmt.Sprintf("update %s set `del_flag` = ? , `last_update_by` = ?, `last_update_time` = ? where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, data.DelFlag, data.LastUpdateBy, data.LastUpdateTime, data.Id)
	return err
}

func (m *defaultSysUserModel) FindOne(ctx context.Context, id int64) (*SysUser, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysUserRows, m.table)
	var resp SysUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserModel) FindOneByName(ctx context.Context, name string) (*SysUser, error) {
	var resp SysUser
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", sysUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserModel) FindAll(ctx context.Context, sysUserQuery *SysUserQuery, Current int64, PageSize int64) (*[]SysUserList, error) {

	search := ""
	if len(sysUserQuery.Name) > 0 {
		search += fmt.Sprintf(" and `name` LIKE '%s'", "%"+sysUserQuery.Name+"%")
	}
	if len(sysUserQuery.NickName) > 0 {
		search += fmt.Sprintf(" and `nick_name` LIKE '%s'", "%"+sysUserQuery.NickName+"%")
	}
	if len(sysUserQuery.Email) > 0 {
		search += fmt.Sprintf(" and `email` LIKE '%s'", "%"+sysUserQuery.Email+"%")
	}
	if len(sysUserQuery.Mobile) > 0 {
		search += fmt.Sprintf(" and `mobile` LIKE '%s'", "%"+sysUserQuery.Mobile+"%")
	}
	if enumx.CheckValueInUserStatusEnum(sysUserQuery.Status) {
		search += fmt.Sprintf(" and `status` = %d", sysUserQuery.Status)
	}

	query := fmt.Sprintf("select %s from %s where `del_flag` = 0 %s limit ?,?", sysUserRows, m.table, search)
	//query := "select sys_user.*, ifnull(sj.job_name,'') as job_name, ifnull(sd.name ,'')as dept_name, ifnull(sys_role.name,'') as role_name,ifnull(sys_role.id ,'1')as role_id from sys_user   left join sys_user_role sur on sys_user.id = sur.user_id   left join sys_role on sur.role_id = sys_role.id    left join sys_job sj on sys_user.job_id = sj.id left join sys_dept sd on sys_user.dept_id = sd.id limit ?,?"
	var resp []SysUserList
	err := m.conn.QueryRowsCtx(ctx, &resp, query, (Current-1)*PageSize, PageSize)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserModel) Count(ctx context.Context, sysUserQuery *SysUserQuery) (int64, error) {
	search := ""
	if len(sysUserQuery.Name) > 0 {
		search += fmt.Sprintf(" and `name` LIKE '%s'", "%"+sysUserQuery.Name+"%")
	}
	if len(sysUserQuery.NickName) > 0 {
		search += fmt.Sprintf(" and `nick_name` LIKE '%s'", "%"+sysUserQuery.NickName+"%")
	}
	if len(sysUserQuery.Email) > 0 {
		search += fmt.Sprintf(" and `email` LIKE '%s'", "%"+sysUserQuery.Email+"%")
	}
	if len(sysUserQuery.Mobile) > 0 {
		search += fmt.Sprintf(" and `mobile` LIKE '%s'", "%"+sysUserQuery.Mobile+"%")
	}
	if enumx.CheckValueInUserStatusEnum(sysUserQuery.Status) {
		search += fmt.Sprintf(" and `status` = %d", sysUserQuery.Status)
	}

	query := fmt.Sprintf("select count(*) as count from %s where `del_flag` = 0 %s", m.table, search)

	var count int64
	err := m.conn.QueryRowCtx(ctx, &count, query)

	switch err {
	case nil:
		return count, nil
	case sqlc.ErrNotFound:
		return 0, ErrNotFound
	default:
		return 0, err
	}
}

func (m *defaultSysUserModel) Insert(ctx context.Context, data *SysUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.NickName, data.Avatar, data.Password, data.Salt, data.Email, data.Mobile, data.Status, data.DeptId, data.CreateBy, data.LastUpdateBy, data.LastUpdateTime, data.DelFlag, data.JobId)
	return ret, err
}

func (m *defaultSysUserModel) Update(ctx context.Context, newData *SysUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.NickName, newData.Avatar, newData.Password, newData.Salt, newData.Email, newData.Mobile, newData.Status, newData.DeptId, newData.CreateBy, newData.LastUpdateBy, newData.LastUpdateTime, newData.DelFlag, newData.JobId, newData.Id)
	return err
}

func (m *defaultSysUserModel) tableName() string {
	return m.table
}
